steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - "build"
          - "-t"
          - "gcr.io/$PROJECT_ID/meme-app:$COMMIT_SHA"
          - "."
    - name: gcr.io/cloud-builders/docker
      args:
          - "push"
          - "gcr.io/$PROJECT_ID/meme-app:$COMMIT_SHA"
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "run"
          - "deploy"
          - "meme-app"
          - "--image=gcr.io/$PROJECT_ID/meme-app:$COMMIT_SHA"
          - "--region=us-central1"
          - "--cpu=2"
          - "--memory=2048Mi"
          - "--allow-unauthenticated"
          - "--set-secrets=DB_HOST=db_host:latest,DB_PORT=db_port:latest,DB_USERNAME=db_username:latest,DB_PASSWORD=db_password:latest,APP_KEY=meme_app_key:latest"
images:
    - "gcr.io/$PROJECT_ID/meme-app:$COMMIT_SHA"
logsBucket: "gs://meme-buckets/logs"
